module.exports = {
  USERNAME: "postgres",
  PASSWORD: "ernestbiscuitdata",
  DB: "ikea",
  PORT: 3001,
  dialect: "postgres",
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000,
  },
  jwt: "dev-jwt",
  BASE_URL: ``,
  FRONT_URL: "",
  MAILUSER: "",
  MAILPASS: "",
  DATAFORSEO_USERNAME: "",
  DATAFORSEO_PASSWORD: "",
  SECRET_TOKEN: "RANDOM_TOKEN_SECRET",
  INSTANCE_CONNECTION_NAME_DEV: "35.189.90.252",
  INSTANCE_CONNECTION_NAME_PROD: "earnest-mark-285609:europe-west2:bd1",
  NODE_ENV: "production",
  BUCKET: "filesbiscuitdata",
  PROJECTID: "earnest-mark-285609",
}
